### ISSUE TITLE
好像缺少文件

### ISSUE THREAD

**Issue by PKQ1688** [linancn/TianGong-AI-Unstructure#6]
git里没有src/tools/embedding.py 这个文件

**Comment by Rachum-thu** [comment]
哥们，我这毕设做着玩的项目都被你发现了

**Comment by linancn** [comment]
removed~

**Comment by PKQ1688** [comment]
哈哈哈哈 我也是参考你这个做自己的毕设

Runchu Tian ***@***.***> 于2024年4月15日周一 20:22写道：
